from math import exp, tanh

SIGMOID = lambda x: 1 / (1 + exp(-x))
TANH = tanh

INPUT_SIZE = 27
OUTPUT_SIZE = 2
MAX_CLIENTS = 1000
GENERATIONS = 40

MAX_NODES = 2 ** 20
c1, c2, c3 = 1, 1, 1
CP = 3

WEIGHT_SHIFT_STRENGTH = 0.7
WEIGHT_RANDOM_STRENGTH = 0.5

SURVIVORS = 0.6

PROBABILITY_MUTATE_LINK = 0.02
PROBABILITY_MUTATE_NODE = 0.015
PROBABILITY_MUTATE_WEIGHT_SHIFT = 0.08
PROBABILITY_MUTATE_WEIGHT_RANDOM = 0.04
PROBABILITY_MUTATE_TOGGLE_LINK = 0.02

ACTIVATION_FUNCTION = TANH
